const keysData = {
numberRow: [
    {id: 1 , key: '`', code: 'Backquote', shift: '¬', color: 'l'},
    {id: 2 , key: "1", code: "Digit1", shift: '!', color: 'l1'},
    {id: 3 , key: "2", code: "Digit2", shift: '@', color: 'l1'},
    {id: 4 , key: "3", code: "Digit3", shift: '#', color: 'l2'},
    {id: 5 , key: "4", code: "Digit4", shift: '$', color: 'l3'},
    {id: 6 , key: "5", code: "Digit5", shift: '%', color: 'l4'},
    {id: 7 , key: "6", code: "Digit6", shift: '^', color: 'l4'},
    {id: 8 , key: "7", code: "Digit7", shift: '&', color: 'r4'},
    {id: 9 , key: "8", code: "Digit8", shift: '*', color: 'r4'},
    {id: 10 , key: "9", code: "Digit9", shift: '(', color: 'r3'},
    {id: 11 , key: "0", code: "Digit0", shift: ')', color: 'r2'},
    {id: 12 , key: "-", code: "Minus", shift: '_', color: 'r1'},
    {id: 13 , key: "=", code: "Equal", shift: '+', color: 'r1'},
    {id: 14 , key: "Backspace", code: "Backspace",  shift: 'Backspace', color: 'r1'}
],
upperRow: [
    {id: 1, key: 'Tab', shift: 'Tab', color: 'l1', code: 'Tab'},
    {id: 2, key: "q", code: "KeyQ", shift: 'Q', color: 'l1'},
    {id: 3, key: "w", code: "KeyW", shift: 'W', color: 'l2'},
    {id: 4, key: "e", code: "KeyE", shift: 'E', color: 'l3'},
    {id: 5, key: "r", code: "KeyR", shift: 'R', color: 'l4'},
    {id: 6, key: "t", code: "KeyT", shift: 'T', color: 'l4'},
    {id: 7, key: "y", code: "KeyY", shift: 'Y', color: 'r4'},
    {id: 8, key: "u", code: "KeyU", shift: 'U', color: 'r4'},
    {id: 9, key: "i", code: "KeyI", shift: 'I', color: 'r3'},
    {id: 10, key: "o", code: "KeyO", shift: 'O', color: 'r2'},
    {id: 11, key: "p", code: "KeyP", shift: 'P', color: 'r1'},
    {id: 12, key: "[", code: "BracketLeft", shift: '{', color: 'r1'},
    {id: 13, key: "]", code: "BracketRight", shift: '}', color: 'r1'},
    {id: 14, key: "Enter", code: "Enter", shift: 'Enter', color: 'r1'},
],
middleRow: [
    {id: 1, key: "CapsLock", code: "CapsLock", shift: 'CapsLock', color: 'l1'},
    {id: 2, key: "a", code: "KeyA", shift: 'A', color: 'l1'},
    {id: 3, key: "s", code: "KeyS", shift: 'S', color: 'l2'},
    {id: 4, key: "d", code: "KeyD", shift: 'D', color: 'l3'},
    {id: 5, key: "f", code: "KeyF", shift: 'F', color: 'l4'},
    {id: 6, key: "g", code: "KeyG", shift: 'G', color: 'l4'},
    {id: 7, key: "h", code: "KeyH", shift: 'H', color: 'r4'},
    {id: 8, key: "j", code: "KeyJ", shift: 'J', color: 'r4'},
    {id: 9, key: "k", code: "KeyK", shift: 'K', color: 'r3'},
    {id: 10, key: "l", code: "KeyL", shift: 'L', color: 'r2'},
    {id: 11, key: ";", code: "Semicolon", shift: ':', color: 'r1'},
    {id: 12, key: "'", code: "Quote", shift: '"', color: 'r1'},
    {id: 13, key: "\\", code: "Backslash", shift: '|', color: 'r1'},
],
lowerRow: [
    {id: 1, key: "Shift", code: "ShiftLeft", shift: "Shift", color: "l1"},
    {id: 2, key: "\\", code: "IntlBackslash", shift: "|" , color: "l1"},
    {id: 3, key: "z", code: "KeyZ", shift: "Z", color: "l1"},
    {id: 4, key: "x", code: "KeyX", shift: "X", color: "l2"},
    {id: 5, key: "c", code: "KeyC", shift: "C", color: "l3"},
    {id: 6, key: "v", code: "KeyV", shift: "V", color: "l4"},
    {id: 7, key: "b", code: "KeyB", shift: "B", color: "l4"},
    {id: 8, key: "n", code: "KeyN", shift: "N", color: "r4"},
    {id: 9, key: "m", code: "KeyM", shift: "M", color: "r4"},
    {id: 10, key: ",", code: "Comma", shift: "<", color: "r3"},
    {id: 11, key: ".", code: "Period", shift: ">", color: "r2"},
    {id: 12, key: "/", code: "Slash", shift: "?", color: "r1"},
    {id: 13, key: "Shift", code: "ShiftRight", shift: "Shift", color: "r1"}
],
bottomRow: [
    {id: 1, key: "Control", code: "ControlLeft", shift: "Control", color: "l1"},
    {id: 2, key: "Win", code: "###", shift: "Win", color: "l1"},
    {id: 3, key: "Alt", code: "AltLeft", shift: "Alt", color: "l2"},
    {id: 4, key: " ", code: "Space", shift: " ", color: "t"},
    {id: 5, key: "Alt", code: "AltRight", shift: "Alt", color: "r2"},
    {id: 6, key: "Win", code: "###", shift: "Win", color: "r1"},
    {id: 7, key: "###", code: "###", shift: "###", color: "r1"},
    {id: 8, key: "Control", code: "ControlRight", shift: "Control", color: "r1"}
]
}

export default keysData;