const characters = {
    'a': ['KeyA'],
    'b': ['KeyB'],
    'c': ['KeyC'],
    'd': ['KeyD'],
    'e': ['KeyE'],
    'f': ['KeyF'],
    'g': ['KeyG'],
    'h': ['KeyH'],
    'i': ['KeyI'],
    'j': ['KeyJ'],
    'k': ['KeyK'],
    'l': ['KeyL'],
    'm': ['KeyM'],
    'n': ['KeyN'],
    'o': ['KeyO'],
    'p': ['KeyP'],
    'q': ['KeyQ'],
    'r': ['KeyR'],
    's': ['KeyS'],
    't': ['KeyT'],
    'u': ['KeyU'],
    'v': ['KeyV'],
    'w': ['KeyW'],
    'x': ['KeyX'],
    'y': ['KeyY'],
    'z': ['KeyZ'],
    'A': ['KeyA', 'ShiftRight'],
    'B': ['KeyB', 'ShiftRight'],
    'C': ['KeyC', 'ShiftRight'],
    'D': ['KeyD', 'ShiftRight'],
    'E': ['KeyE', 'ShiftRight'],
    'F': ['KeyF', 'ShiftRight'],
    'G': ['KeyG', 'ShiftRight'],
    'H': ['KeyH', 'ShiftLeft'],
    'I': ['KeyI', 'ShiftLeft'],
    'J': ['KeyJ', 'ShiftLeft'],
    'K': ['KeyK', 'ShiftLeft'],
    'L': ['KeyL', 'ShiftLeft'],
    'M': ['KeyM', 'ShiftLeft'],
    'N': ['KeyN', 'ShiftLeft'],
    'O': ['KeyO', 'ShiftLeft'],
    'P': ['KeyP', 'ShiftLeft'],
    'Q': ['KeyQ', 'ShiftRight'],
    'R': ['KeyR', 'ShiftRight'],
    'S': ['KeyS', 'ShiftRight'],
    'T': ['KeyT', 'ShiftRight'],
    'U': ['KeyU', 'ShiftLeft'],
    'V': ['KeyV', 'ShiftRight'],
    'W': ['KeyW', 'ShiftRight'],
    'X': ['KeyX', 'ShiftRight'],
    'Y': ['KeyY', 'ShiftLeft'],
    'Z': ['KeyZ', 'ShiftRight'],
    '`': ['Backquote'],
    '1': ['Digit1'],
    '2': ['Digit2'],
    '3': ['Digit3'],
    '4': ['Digit4'],
    '5': ['Digit5'],
    '6': ['Digit6'],
    '7': ['Digit7'],
    '8': ['Digit8'],
    '9': ['Digit9'],
    '0': ['Digit0'],
    '-': ['Minus'],
    '=': ['Equal'],
    '~': ['Backquote', 'ShiftRight'],
    '!': ['Digit1', 'ShiftRight'],
    '@': ['Digit2', 'ShiftRight'],
    '#': ['Digit3', 'ShiftRight'],
    '$': ['Digit4', 'ShiftRight'],
    '%': ['Digit5', 'ShiftRight'],
    '^': ['Digit6', 'ShiftRight'],
    '&': ['Digit7', 'ShiftLeft'],
    '*': ['Digit8', 'ShiftLeft'],
    '(': ['Digit9', 'ShiftLeft'],
    ')': ['Digit0', 'ShiftLeft'],
    '_': ['Minus', 'ShiftLetft'],
    '+': ['Equal', 'ShiftLetft'],
    ' ': ['Space'],
    '[': ['BracketLeft'],
    ']': ['BracketRight'],
    '{': ['BracketLeft', 'ShiftLeft'],
    '}': ['BracketRight', 'ShiftLeft'],
    ';': ['Semicolon'],
    "'": ['Quote'],
    '\\': ['Backslash'],
    ':': ['Semicolon', 'ShiftLeft'],
    '"': ['Quote', 'ShiftLeft'],
    '|': ['Backslash', 'ShiftLeft'],
    ',': ["Comma"],
    '.': ["Period"],
    '/': ["Slash"],
    '<': ["Comma", 'ShiftLeft'],
    '>': ["Period", 'ShiftLeft'],
    '?': ["Slash", 'ShiftLeft'],
    '\n': ['Enter'],
    'Tab': ['Tab'],
    "CapsLock": ["CapsLock"],
    "Control": ["Control"],
    "Alt": ["Alt"],
    "Shift": ["Shift"],
    "Enter": ["Enter"],
    Ignored: ["Shift", "Alt", "Control", "CapsLock", 'Tab']
};


export default characters;